"""Add user_id to Title

Revision ID: 9035e86ddbc1
Revises: 5d2d5667c2c6
Create Date: 2025-07-22 22:14:49.859626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9035e86ddbc1'
down_revision = '5d2d5667c2c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
